# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeadapt < Formula
  desc "Kubeadapt CLI for Kubernetes cost optimization"
  homepage "https://kubeadapt.io"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.2.0/kubeadapt_0.2.0_darwin_amd64.tar.gz"
      sha256 "45fd308f3e956bb6d05a9762401f5c7d0a19d203d743add7db54e396b763979e"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.2.0/kubeadapt_0.2.0_darwin_arm64.tar.gz"
      sha256 "6ba9304532d8aaca4f63e353ed0c70661d6b5f9238e98496fff43cf8bdb1e45f"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.2.0/kubeadapt_0.2.0_linux_amd64.tar.gz"
      sha256 "e55a128302bfad373f68f6066995e9b0bcb5809095cd46488024fbe016c1f206"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.2.0/kubeadapt_0.2.0_linux_arm64.tar.gz"
      sha256 "36c7b821110d3293c81c9527a0939dd3947f2b30a65818e9c82786b87aa487b9"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  test do
    system "#{bin}/kubeadapt", "version"
  end
end
