# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeadapt < Formula
  desc "Kubeadapt CLI for Kubernetes cost optimization"
  homepage "https://kubeadapt.io"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt_0.1.0_darwin_amd64.tar.gz"
      sha256 "12475ac28be868ff9c477dcf8983f62c5c18637b35d8437215fa1b87b9de8aa2"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt_0.1.0_darwin_arm64.tar.gz"
      sha256 "f058caaff29056dd628726d8551fb55942b05fc17aa6114bcc0c548d7476ee9e"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt_0.1.0_linux_amd64.tar.gz"
      sha256 "66987570d5dad1777a4ff181411e27cc45dadff2e304f2b4c9e49bcccfe61cc3"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt_0.1.0_linux_arm64.tar.gz"
      sha256 "c371d3a4409c51f7b72de2c256d7133f390085baaffaef043f19db3ddf87b36a"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  test do
    system "#{bin}/kubeadapt", "version"
  end
end
