# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeadapt < Formula
  desc "Kubeadapt CLI for Kubernetes cost optimization"
  homepage "https://kubeadapt.io"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.4/kubeadapt_0.1.4_darwin_amd64.tar.gz"
      sha256 "cb2440b1466c94698d1c3cb26037b9b5987d69f148083b904ae8a44be00367e1"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.4/kubeadapt_0.1.4_darwin_arm64.tar.gz"
      sha256 "0723452334d614174cfdd5a66c504a401e2684b6095e54efe8e47eab05ef1943"

      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.4/kubeadapt_0.1.4_linux_amd64.tar.gz"
      sha256 "1244041ac4b863fb3b50e9cdc860758bc4917dce1fd0c099c72a7b8ff8f73d6c"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.4/kubeadapt_0.1.4_linux_arm64.tar.gz"
      sha256 "cb4aa1b73ba90974d1c7fdedc872eeb21dd38a2d435a89ff68ba10be5479fdb3"
      define_method(:install) do
        bin.install "kubeadapt"
      end
    end
  end

  test do
    system "#{bin}/kubeadapt", "version"
  end
end
