# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeadaptCli < Formula
  desc "KubeAdapt CLI for Kubernetes cost optimization"
  homepage "https://kubeadapt.io"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "27533a6e0981430b9da2042aa9c3f0bbe007e3f5a4cf4cfd88ce9915d05bf9a2"

      define_method(:install) do
        bin.install "kubeadapt-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "286258330896c0d8ecf14589de1a2d974b4e8331dcc646993ce29ee742b783be"

      define_method(:install) do
        bin.install "kubeadapt-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "915a798a25fd86d9d2458277207c42bb6346959e8d7c39b91845f97b5aad7003"
      define_method(:install) do
        bin.install "kubeadapt-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeadapt/kubeadapt-cli/releases/download/v0.1.0/kubeadapt-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "834577037433aaff4a15eb3d14dbf3886f1abff0f23d580693c895b498c67bdc"
      define_method(:install) do
        bin.install "kubeadapt-cli"
      end
    end
  end

  test do
    system "#{bin}/kubeadapt-cli", "version"
  end
end
